version: 2.1
jobs:
  build:
   docker:
      - image: ubuntu:20.04
   
   steps:
      - run:
          name: "dump_vendor"
          command: |
            apt-get update -y && apt-get upgrade -y && apt-get install wget curl git zip unzip gcc build-essential bc sudo python3 python3-pip -y
            sudo apt install unace unrar zip unzip p7zip-full p7zip-rar sharutils rar uudeview mpack arj cabextract rename -y
            sudo apt install liblzma-dev python3-pip brotli lz4 -y
            pip install backports.lzma protobuf pycrypto twrpdtgen extract-dtb 
            export DEBIAN_FRONTEND=noninteractive
            apt-get install tzdata -y
            
            git config --global user.name "test"
            git config --global user.email "test@gmail.com"
            
     
            git clone https://github.com/LineageOS/android_tools_extract-utils -b lineage-18.1 android/tools/extract-utils
            git clone https://github.com/LineageOS/android_prebuilts_extract-tools -b lineage-18.1 android/prebuilts/extract-tools
            
            cd android
            git clone https://gitlab.com/firmware-dump/android_dump_tecno_TECNO-KE6.git device/tecno/TECNO-KE6
            
            bash device/tecno/TECNO-KE6/extract-files.sh 
            ls vendor/tecno/TECNO-KE6
            
            
            
          
